---
name: Defect
description: Report a defect, such as a bug or regression.
labels:
  - defect
body:
  - type: textarea
    id: observed
    attributes:
      label: Observed behavior
      description: Describe the unexpected behavior or performance regression you are observing.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe the expected behavior or performance characteristics.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Server and client version
      description: |-
        Provide the versions you were using when the detect was observed.
        For the server, use `nats-server --version`, check the startup log output, or the image tag pulled from Docker.
        For the CLI client, use `nats --version`.
        For language-specific clients, check the version downloaded by the language dependency manager.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Host environment
      description: |-
        Specify any relevant details about the host environment the server and/or client was running in,
        such as operating system, CPU architecture, container runtime, etc.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide as many concrete steps to reproduce the defect.
    validations:
      required: false
